version: '3'

services:
  nginx:
    image: nginx:alpine
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"

  drummerei:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - nginx
