# Generated by Django 5.1.5 on 2025-01-22 14:39

import datetime
import drummerei.models.settings
import drummerei.models.slot
import drummerei.models.schedule
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Drummerei', max_length=255)),
                ('subtitle', models.CharField(default='Open Decks Timetable', max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('default_start_time', models.TimeField(default=datetime.time(20, 0))),
                ('default_duration', models.DurationField(default=datetime.timedelta(seconds=14400))),
                ('default_slot_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField(default=drummerei.models.slot.generate_start_time)),
                ('slot_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(default=drummerei.models.schedule.generate_pin)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('slots', models.ManyToManyField(blank=True, null=True, to='drummerei.slot')),
            ],
        ),
    ]
