# Generated by Django 5.1.5 on 2025-01-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_qr_code_path',
            field=models.CharField(default='drummerei/static/image/qr.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slots',
            field=models.ManyToManyField(editable=False, to='drummerei.slot'),
        ),
    ]
