# Generated by Django 5.1.5 on 2025-01-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('slots', models.ManyToManyField(to='drummerei.slot')),
            ],
        ),
    ]
