# Generated by Django 5.1.5 on 2025-01-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slots',
            field=models.ManyToManyField(blank=True, null=True, to='drummerei.slot'),
        ),
    ]
