# Generated by Django 5.1.5 on 2025-01-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0003_alter_settings_default_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='url',
            field=models.CharField(default='http://druckse/ledwand', help_text='The URL associated with the application.', max_length=255),
        ),
    ]
