# Generated by Django 5.1.5 on 2025-01-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0004_schedule_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pin',
            field=models.IntegerField(default=4711),
        ),
    ]
