# Generated by Django 5.1.5 on 2025-01-28 17:34

import drummerei.models.schedule
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0004_alter_settings_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='unlock_hours',
            field=models.IntegerField(default=1, help_text='The number of hours before the start time when slots can be unlocked.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=drummerei.models.schedule.generate_end_time),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=drummerei.models.schedule.generate_start_time),
        ),
    ]
