# Generated by Django 5.1.5 on 2025-01-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0005_slot_available_alter_schedule_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pin',
            field=models.IntegerField(default=9258),
        ),
    ]
