# Generated by Django 5.1.5 on 2025-01-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0005_settings_unlock_hours_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='unlock_hours',
            new_name='default_unlock_hours',
        ),
    ]
