# Generated by Django 5.1.5 on 2025-01-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0006_slot_slot_id_alter_schedule_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='available',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pin',
            field=models.IntegerField(default=2086),
        ),
    ]
