# Generated by Django 5.1.5 on 2025-01-28 22:38

import drummerei.models.schedule
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0006_rename_unlock_hours_settings_default_unlock_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='unlock_hours',
            field=models.IntegerField(default=drummerei.models.schedule.generate_unlock_hours),
        ),
    ]
