# Generated by Django 5.1.5 on 2025-01-20 01:03

import drummerei.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0008_alter_schedule_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pin',
            field=models.IntegerField(default=drummerei.models.generate_pin),
        ),
    ]
