# Generated by Django 5.1.5 on 2025-01-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0009_alter_schedule_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
