# Generated by Django 5.1.5 on 2025-01-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
