# Generated by Django 5.1.5 on 2025-01-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0011_settings_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
