# Generated by Django 5.1.5 on 2025-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0012_alter_settings_options_settings_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(default='Drummerei', max_length=255),
        ),
    ]
