# Generated by Django 5.1.5 on 2025-01-20 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0013_alter_settings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=14400)),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_start_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='subtitle',
            field=models.CharField(default='Open Decks Timetable', max_length=255),
        ),
    ]
