# Generated by Django 5.1.5 on 2025-01-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0014_settings_default_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='time',
        ),
    ]
