# Generated by Django 5.1.5 on 2025-01-20 21:28

import drummerei.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0015_remove_slot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(default=drummerei.models.generate_start_time),
        ),
    ]
