# Generated by Django 5.1.5 on 2025-01-20 21:32

import drummerei.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0016_slot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slots',
            field=models.ManyToManyField(default=drummerei.models.generate_slots, to='drummerei.slot'),
        ),
    ]
