# Generated by Django 5.1.5 on 2025-01-20 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0017_alter_schedule_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_slot_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
