# Generated by Django 5.1.5 on 2025-01-20 22:17

import drummerei.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummerei', '0018_settings_default_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slots',
            field=models.ManyToManyField(blank=True, default=drummerei.models.generate_slots, null=True, to='drummerei.slot'),
        ),
    ]
